### ISSUE TITLE
Reset dashboard on data change

### ISSUE THREAD

**Issue by franksh** [scazachariae/kira-dashboard#18]
The outbreak location can currently be selected from a dropdown. This reloads the correct data, which is so far correctly displayed on the map when the slider is moved, but not everything is considered

The data change should:
- reset the timer to 0
- show the correct heatmap/cloropleth immediately
- update the tables
- Maybe display a message "New oubtreak location X loaded" (see Angular Material Snack bar https://material.angular.io/components/snack-bar/overview)

The change event should be properly implemented and propagate through the dashboard, starting with simulation data service

**Comment by scazachariae** [comment]
We should definitly remove the event emitter when the data is loaded correctly

**Comment by franksh** [comment]
Sure, you can go ahead and do that
